language: ruby

node_js:
  - "8"

addons:
  firefox: "latest"

cache: bundler

rvm:
  - 2.3

install:
  - bundle install --path vendor/bundle
  - bundle update rubocop
  - npm install -g ember-cli
  - npm i -g npm
  - npm --prefix ./frontend install ./frontend

services:
  - sh -e /etc/init.d/xvfb start

before_script:
  - export DISPLAY=:99.0
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:setup

script:
  - bundle --deployment
  - JOBS=1 bundle exec rake ci
