default: &default
  adapter: <%= ENV['RAILS_DB_ADAPTER'] || 'postgresql' %>
  host: <%= ENV['RAILS_DB_HOST'] || '127.0.0.1' %>
  port: <%= ENV['RAILS_DB_PORT'] || 5432 %>
  username: <%= ENV['RAILS_DB_USERNAME'] || "skills" %>
  password: <%= ENV['RAILS_DB_PASSWORD'] || "skills" %>
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: <%= "#{ENV['RAILS_DEV_DB_NAME'] || 'skills_development'}#{ENV['TEST_ENV_NUMBER']}" %>

test:
  <<: *default
  database: <%= "#{ENV['RAILS_TEST_DB_NAME'] || 'skills_test'}#{ENV['TEST_ENV_NUMBER']}" %>

production:
  <<: *default
  database: <%= ENV['RAILS_DB_NAME'] || "skills_production" %>
