categories:
  UX Design:
    - UX Methoden
    - UX Tools
  Software Engineering:
    - Java
    - Ruby
    - Frontend / JavaScript
    - Multiplatform Apps
    - Web- & Application Server
    - Streaming & Messaging
    - Datenbanken / DB-Server
    - Machine Learning / AI
    - Lightning Network
  Delivery:
    - CI/CD
    - Container Platforms & Engineering
  System Engineering:
    - Cloud-, Configuration- & Worflow Managment
    - Linux Engineering
    - Virtualisierung & HA
    - Monitoring & Reporting
    - Security & Auth
    - Networking
  Diverses:
    - Sprachen & Syntax
    - Tools
    - Methoden
    - Ohne Kategorie

radar:
  - adopt
  - trial
  - assess
  - hold
  - n/a

portfolio:
  - aktiv
  - passiv
  - abbauen
  - nein
